# EmbedExtAPI.cmake
#
# Reads the LLVM text-IR file at INPUT_FILE and writes a C++ source file at
# OUTPUT_FILE that embeds the IR content as a raw-string literal.
#
# Invoked as: cmake -DINPUT_FILE=<path> -DOUTPUT_FILE=<path> -P EmbedExtAPI.cmake

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "EmbedExtAPI.cmake requires -DINPUT_FILE and -DOUTPUT_FILE")
endif()

if(NOT EXISTS "${INPUT_FILE}")
  message(FATAL_ERROR "EmbedExtAPI.cmake: input file does not exist: ${INPUT_FILE}")
endif()

file(READ "${INPUT_FILE}" EXTAPI_IR_CONTENT)
string(LENGTH "${EXTAPI_IR_CONTENT}" EXTAPI_IR_LEN)

string(FIND "${EXTAPI_IR_CONTENT}" ")SVFEXTAPI\"" _delim_pos)
if(NOT _delim_pos EQUAL -1)
  message(FATAL_ERROR "EmbedExtAPI.cmake: raw-string delimiter found in IR content")
endif()

file(WRITE "${OUTPUT_FILE}"
  "// Auto-generated by EmbedExtAPI.cmake. Do not edit.\n"
  "#include <cstddef>\n"
  "\n"
  "extern const char extapi_ir_data[];\n"
  "extern const size_t extapi_ir_size;\n"
  "\n"
  "const char extapi_ir_data[] = R\"SVFEXTAPI("
)

file(APPEND "${OUTPUT_FILE}" "${EXTAPI_IR_CONTENT}")

file(APPEND "${OUTPUT_FILE}"
  ")SVFEXTAPI\";\n"
  "\n"
  "const size_t extapi_ir_size = sizeof(extapi_ir_data) - 1;\n"
)

message(STATUS "EmbedExtAPI: embedded ${EXTAPI_IR_LEN} bytes of IR into ${OUTPUT_FILE}")
